var menu = [
	{ id: 1, name: '全部商品分类' },
	{ id: 2, name: '小米手机' },
	{ id: 3, name: '红米' },
	{ id: 4, name: '电视' },
	{ id: 5, name: '笔记本' },
	{ id: 6, name: '家电' },
	{ id: 7, name: '新品' },
	{ id: 8, name: '路由器' },
	{ id: 9, name: '智能硬件' },
	{ id: 10, name: '服务' },
	{ id: 11, name: '社区' }
];
var menuSub = [
	// 小米手机
	{ 
		cid: 2,
		brief: '新品',
		avatar: '../mi9/images/xm/xm1.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 2,
		brief: '新品',
		avatar: '../mi9/images/xm/xm2.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 2,
		brief: '新品',
		avatar: '../mi9/images/xm/xm3.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 2,
		brief: '新品',
		avatar: '../mi9/images/xm/xm4.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 2,
		avatar: '../mi9/images/xm/xm5.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 2,
		avatar: '../mi9/images/xm/xm6.png', 
		name: '' ,
		price: '' ,
	},
	// 红米手机
	{ 
		cid: 3,
		brief: '新品',
		avatar: '../mi9/images/redmi/redmi1.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 3,
		brief: '新品',
		avatar: '../mi9/images/redmi/redmi2.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 3,
		brief: '新品',
		avatar: '../mi9/images/redmi/redmi3.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 3,
		avatar: '../mi9/images/redmi/redmi4.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 3,
		avatar: '../mi9/images/redmi/redmi5.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 3,
		avatar: '../mi9/images/redmi/redmi6.png', 
		name: '' ,
		price: '' ,
	},
	// 电视
	{ 
		cid: 4,
		brief: '新品',
		avatar: '../mi9/images/TV/TV1.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 4,
		brief: '新品',
		avatar: '../mi9/images/TV/TV2.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 4,
		brief: '热卖',
		avatar: '../mi9/images/TV/TV3.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 4,
		brief: '热卖',
		avatar: '../mi9/images/TV/TV4.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 4,
		brief: '热卖',
		avatar: '../mi9/images/TV/TV5.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 4,
		avatar: '../mi9/images/TV/TV6.png', 
		name: '' ,
		price: '' ,
	},
	// 笔记本
	{ 
		cid: 5,
		brief: '新品',
		avatar: '../mi9/images/laptop/top1.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 5,
		brief: '新品',
		avatar: '../mi9/images/laptop/top2.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 5,
		brief: '新品',
		avatar: '../mi9/images/laptop/top3.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 5,
		brief: '新品',
		avatar: '../mi9/images/laptop/top4.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 5,
		avatar: '../mi9/images/laptop/top5.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 5,
		avatar: '../mi9/images/laptop/top6.png', 
		name: '' ,
		price: '' ,
	},
	// 家电
	{ 
		cid: 6,
		avatar: '../mi9/images/household/household1.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 6,
		avatar: '../mi9/images/household/household2.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 6,
		avatar: '../mi9/images/household/household3.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 6,
		avatar: '../mi9/images/household/household4.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 6,
		avatar: '../mi9/images/household/household5.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 6,
		avatar: '../mi9/images/household/household6.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 7,
		avatar: '../mi9/images/new/new1.jpg', 
		name: '' ,
		price: '' ,
	},
	// 新品
	{ 
		cid: 7,
		brief: '新品',
		avatar: '../mi9/images/new/new2.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 7,
		brief: '新品',
		avatar: '../mi9/images/new/new3.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 7,
		brief: '新品',
		avatar: '../mi9/images/new/new4.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 7,
		avatar: '../mi9/images/new/new5.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 7,
		avatar: '../mi9/images/new/new6.jpg', 
		name: '' ,
		price: '' ,
	},
	// 路由器
	{ 
		cid: 8,
		brief: '新品',
		avatar: '../mi9/images/router/router1.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 8,
		brief: '双频双核',
		avatar: '../mi9/images/router/router2.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 8,
		avatar: '../mi9/images/router/router3.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 8,
		avatar: '../mi9/images/router/router4.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 8,
		brief: '大容量',
		avatar: '../mi9/images/router/router5.png', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 8,
		avatar: '../mi9/images/router/router6.png', 
		name: '' ,
		price: '' ,
	},
	// 智能硬件
	{ 
		cid: 9,
		avatar: '../mi9/images/ai/ai1.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 9,
		avatar: '../mi9/images/ai/ai2.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 9,
		avatar: '../mi9/images/ai/ai3.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 9,
		avatar: '../mi9/images/ai/ai4.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 9,
		avatar: '../mi9/images/ai/ai5.jpg', 
		name: '' ,
		price: '' ,
	},
	{ 
		cid: 9,
		avatar: '../mi9/images/ai/ai6.jpg', 
		name: '' ,
		price: '' ,
	}
];
